# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build and publish .netcore function'
  inputs:
    command: 'build'
    projects: 'FunctionAvailabilityTests'
    arguments: '-c Release --output $(Build.ArtifactStagingDirectory)/publish'
- task: ArchiveFiles@2
  displayName: 'Archive .netcore function to $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
# Copy Files
# Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    #sourceFolder: # Optional
    contents: |
     azuredeploy.json
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true # Optional
    overWrite: true # Optional
    #flattenFolders: false # Optional
- task: PublishBuildArtifacts@1
  displayName: 'Publish $(Build.ArtifactStagingDirectory)'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 